### ISSUE TITLE
MongoDB：使用 Docker 搭建 MongoDB （副本集+分片集）集群

### ISSUE THREAD

**Issue by yifanzheng** [yifanzheng/BigData-Notes#5]
## MongoDB 集群搭建

在三台 Linux 服务器上搭建 MongoDB 分布式集群，采用副本集+分片集群方式进行部署，并设置密码认证，以实现生产环境上的高可用。

### 集群规划

node1 实例 | node2 实例 | node3 实例 | 端口 | 副本集
-- | -- | -- | -- | --
mongos | mongos | mongos | 27014 |  
config | config | config | 27015 | config
shard1 主 | shard1 副 | shard1 仲裁 | 27016 | shard1
shard2 仲裁 | shard2 主 | shard2 副 | 27002 | shard2
shard3 副 | shard3仲 裁 | shard3 主 | 27003 | shard3

### 安装部署

> 注意：以下操作在三台服务器上都要吗执行一次。

**准备镜像**

镜像地址：https://hub.docker.com/_/mongo?tab=tags&page=1&ordering=last_updated
```bash
docker pull mongo
```

**建立数据目录**
```bash
sudo mkdir -p /tmp/mongodb_config
sudo mkdir -p /tmp/mongodb_shard1
sudo mkdir -p /tmp/mongodb_shard2
sudo mkdir -p /tmp/mongodb_shard3
sudo mkdir -p /tmp/mongodb_mongos
sudo mkdir -p /mongodb/keyfile
sudo mkdir -p /mongodb/mongos/log
sudo mkdir -p /mongodb/config/log
sudo mkdir -p /mongodb/config/data
sudo mkdir -p /mongodb/shard1/log
sudo mkdir -p /mongodb/shard1/data
sudo mkdir -p /mongodb/shard2/log
sudo mkdir -p /mongodb/shard2/data
sudo mkdir -p /mongodb/shard3/log
sudo mkdir -p /mongodb/shard3/data
```
目录说明：
- /tmp/mongodb_xxx：用于存放 unix socket
- /mongodb/keyfile：用于存放认证文件
- /mongdb/xxx/log：用于存放日志文件
- /mongodb/xxx/data：用于存放数据文件

**生成认证文件**
```bash
sudo openssl rand -base64 756 -out /mongodb/keyfile/mongodb.key
sudo chmod 400 /mongodb/keyfile/mongodb.key
```
由于认证文件在每台服务器上必须相同，所以可以使用以下命令将文件复制到其他服务器：
```bash
sudo scp /mongodb/keyfile/mongodb.key root@node2:/mongodb/keyfile
```
**配置 Config Server**

编辑生成 Config Server 配置文件 config.conf 至 `/opt/mongodb` 目录
```yml
systemLog:
 destination: file
 logAppend: true
 path: "/mongodb/config/log/config.log"

storage:
 dbPath: /mongodb/config/data
 journal:
  enabled: true
 wiredTiger:
  engineConfig:
   directoryForIndexes: true

processManagement:
 timeZoneInfo: /usr/share/zoneinfo

net:
 port: 27015
 bindIpAll: true
 maxIncomingConnections: 65536
 unixDomainSocket:
  enabled: true
  pathPrefix: /tmp/mongodb_config
  filePermissions: 0700

security:
 keyFile: /mongodb/keyfile/mongodb.key
 clusterAuthMode: keyFile
 authorization: enabled
 javascriptEnabled: true

replication:
 replSetName: config
sharding:
 clusterRole: configsvr
```

**配置 Shard1 Server**

编辑生成 Shard1 Server 配置文件 shard1.conf 至 `/opt/mongodb` 目录
```yml
systemLog:
 destination: file
 logAppend: true
 path: "/mongodb/shard1/log/mongodb.log"

storage:
 dbPath: /mongodb/shard1/data
 journal:
  enabled: true
 wiredTiger:
  engineConfig:
   directoryForIndexes: true     

processManagement:
 timeZoneInfo: /usr/share/zoneinfo

net:
 port: 27016
 bindIpAll: true
 maxIncomingConnections: 65536
 unixDomainSocket:
  enabled: true
  pathPrefix: /tmp/mongodb_shard1
  filePermissions: 0700

security:
 keyFile: /mongodb/keyfile/mongodb.key
 clusterAuthMode: keyFile
 authorization: enabled
 javascriptEnabled: true

replication:
 replSetName: shard1
sharding:
 clusterRole: shardsvr
```

**配置 Shard2 Server**

编辑生成 Shard2 Server 配置文件 shard2.conf 至 `/opt/mongodb` 目录
```yml
systemLog:
 destination: file
 logAppend: true
 path: "/mongodb/shard2/log/mongodb.log"

storage:
 dbPath: /mongodb/shard2/data
 journal:
  enabled: true
 wiredTiger:
  engineConfig:
   directoryForIndexes: true     
processManagement:
 timeZoneInfo: /usr/share/zoneinfo

net:
 port: 27017
 bindIpAll: true
 maxIncomingConnections: 65536
 unixDomainSocket:
  enabled: true
  pathPrefix: /tmp/mongodb_shard2
  filePermissions: 0700

security:
 keyFile: /mongodb/keyfile/mongodb.key
 clusterAuthMode: keyFile
 authorization: enabled
 javascriptEnabled: true

replication:
 replSetName: shard2
sharding:
 clusterRole: shardsvr
```

**配置 Shard3 Server**

编辑生成 Shard3 Server 配置文件 shard3.conf 至 `/opt/mongodb` 目录
```yml
systemLog:
 destination: file
 logAppend: true
 path: "/mongodb/shard3/log/mongodb.log"

storage:
 dbPath: /mongodb/shard3/data
 journal:
  enabled: true
 wiredTiger:
  engineConfig:
   directoryForIndexes: true     

processManagement:
 timeZoneInfo: /usr/share/zoneinfo

net:
 port: 27018
 bindIpAll: true
 maxIncomingConnections: 65536
 unixDomainSocket:
  enabled: true
  pathPrefix: /tmp/mongodb_shard3
  filePermissions: 0700

security:
 keyFile: /mongodb/keyfile/mongodb.key
 clusterAuthMode: keyFile
 authorization: enabled
 javascriptEnabled: true

replication:
 replSetName: shard3
sharding:
 clusterRole: shardsvr
```

**配置 Mongos Server**

编辑生成 Mongos Server 配置文件 mongos.conf 至 `/opt/mongodb` 目录
```yml
systemLog:
 destination: file
 logAppend: true
 path: /mongodb/mongos/log/mongodb.log

processManagement:
 timeZoneInfo: /usr/share/zoneinfo

net:
 port: 27014
 bindIpAll: true
 maxIncomingConnections: 65536
 unixDomainSocket:
  enabled: true
  pathPrefix: /tmp/mongodb_mongos
  filePermissions: 0700

security:
 keyFile: /mongodb/keyfile/mongodb.key
 clusterAuthMode: keyFile

replication:
 localPingThresholdMs: 15

sharding:
 configDB: config/node1:27015,node2:27015,node3:27015
```

**启动各服务**

- 启动 Config Server
```bash
sudo docker run -d -p 27015:27015 --name mongo-configsvr --entrypoint "mongod" -v /opt/mongodb/config.conf:/opt/mongodb/config.conf -v /mongodb/keyfile/mongodb.key:/mongodb/keyfile/mongodb.key -v /mongodb/config/log/config.log:/mongodb/config/log/config.log -v /mongodb/config/data:/mongodb/config/data -v /tmp/mongodb_config:/tmp/mongodb_config a.newegg.org/newegg-docker/mongo -f /opt/mongodb/config.conf
```

- 启动 Shard1 Server
```bash
sudo docker run -d -p 27016:27016 --name mongo-shard1 --entrypoint "mongod" -v /opt/mongodb/shard1.conf:/opt/mongodb/shard1.conf -v /mongodb/keyfile/mongodb.key:/mongodb/keyfile/mongodb.key -v /mongodb/shard1/log/mongodb.log:/mongodb/shard1/log/mongodb.log -v /mongodb/shard1/data:/mongodb/shard1/data -v /tmp/mongodb_shard1:/tmp/mongodb_shard1 a.newegg.org/newegg-docker/mongo -f /opt/mongodb/shard1.conf
```

- 启动 Shard2 Server
```bash
sudo docker run -d -p 27017:27017 --name mongo-shard2 --entrypoint "mongod" -v /opt/mongodb/shard2.conf:/opt/mongodb/shard2.conf -v /mongodb/keyfile/mongodb.key:/mongodb/keyfile/mongodb.key -v /mongodb/shard2/log/mongodb.log:/mongodb/shard2/log/mongodb.log -v /mongodb/shard2/data:/mongodb/shard2/data -v /tmp/mongodb_shard2:/tmp/mongodb_shard2 a.newegg.org/newegg-docker/mongo -f /opt/mongodb/shard2.conf
```

- 启动 Shard3 Server
```bash
sudo docker run -d -p 27018:27018 --name mongo-shard3 --entrypoint "mongod" -v /opt/mongodb/shard3.conf:/opt/mongodb/shard3.conf -v /mongodb/keyfile/mongodb.key:/mongodb/keyfile/mongodb.key -v /mongodb/shard3/log/mongodb.log:/mongodb/shard3/log/mongodb.log -v /mongodb/shard3/data:/mongodb/shard3/data -v /tmp/mongodb_shard3:/tmp/mongodb_shard3 a.newegg.org/newegg-docker/mongo --config /opt/mongodb/shard3.conf
```

- 启动 Mongos Server
```bash
sudo docker run --name mongos -d -p 27014:27014 --entrypoint "mongos" -v /opt/mongodb/mongos.conf:/opt/mongodb/mongos.conf -v /mongodb/keyfile/mongodb.key:/mongodb/keyfile/mongodb.key -v /mongodb/mongos/log/mongodb.log:/mongodb/mongos/log/mongodb.log  -v /tmp/mongodb_mongos:/tmp/mongodb_mongos a.newegg.org/newegg-docker/mongo -f /opt/mongodb/mongos.conf
```

### 配置分片集

>注意：以下操作在任一台服务器上执行一次即可。

**配置 Config 分片**
```bash
sudo docker exec -it mongo-configsvr bash

mongo --port 27015

rs.initiate({
"_id":"config",
"members":[{
	"_id":0,
       "host":"node1:27015"
},{
	"_id":1,
	"host":"node2:27015"
},{
	"_id":2,
	"host":"node3:27015"
}]})
```
**配置 Shard1 分片**

```bash
sudo docker exec -it mongo-shard1 bash

mongo --port 27016

rs.initiate({
_id:"shard1",
members:[{
	_id:0,
       host:"node1:27016"
},{
	_id:1,
	host:"node2:27016"
},{
	_id:2,
	host:"node3:27016",
	arbiterOnly:true
}]})
```

**配置 Shard2 分片**

```bash
sudo docker exec -it mongo-shard2 bash

mongo --port 27017

rs.initiate({
_id:"shard2",
members:[{
	_id:0,
       host:"node1:27017",
       arbiterOnly:true
},{
	_id:1,
	host:"node2:27017"
},{
	_id:2,
	host:"node3:27017"
}]})
```

**配置 Shard3 分片**

```bash
sudo docker exec -it mongo-shard3 bash

mongo --port 27018

rs.initiate({
_id:"shard1",
members:[{
	_id:0,
       host:"node1:27018"
},{
	_id:1,
	host:"node2:27018",
        arbiterOnly:true
},{
	_id:2,
	host:"node3:27018"
}]})
```
执行 rs.status() 可以查看状态。

注意： 对应 Shard1，Shard2，Shard3 分片的配置，如果在同一台服务器上不能一起配置，可以换另一台服务器配置。

**配置 Mongos 分片**
```bash
sudo docker exec -it mongos bash

mongo --port 27014

use admin

sh.addShard("shard1/node1:27016,node2:27016,node3:27016")
sh.addShard("shard2/node1:27017,node2:27017,node3:27017")
sh.addShard("shard3/node1:27018,node2:27018,node3:27018")

sh.status()
```

### 测试

```bash
// 创建管理员账号
db.createUser({user:"admin",pwd:"admin",roles:[{role:"root",db:"admin"}]})

// 登录
mongo node1:27014 -u admin -p admin  --authenticationDatabase admin

// 创建测试数据库
sh.enableSharding("mytest")
sh.shardCollection("mytest.coll1",{"age":1})

//  插入数据
for(var i=1;i<=1000;i++){
db.coll1.insert({
name:i,
age:Math.round(Math.random() * 100),
score1:Math.round(Math.random() * 100),
score2:Math.round(Math.random() * 100),
score3:Math.round(Math.random() * 100),
score4:Math.round(Math.random() * 100),
score5:Math.round(Math.random() * 100)
});
}

db.coll1.find().count()
db.coll1.find().limit(1)
```
